#!/usr/bin/env python3
"""🦋 Draft a catalog specimen from a sealed retraction — the "forgot to collect" guard.

The catalog rule is **no fabrication**: a specimen may only exist if it cites a real,
sealed case (a ledger claim_id + seal, whose git history is the witness). That rule is
exactly why collection gets skipped — writing the provenance by hand at the end of an arc
is friction. This tool removes the friction WITHOUT breaking the rule:

  • it TRANSCRIBES the provable parts — claim_id, seal, retraction reason, ledger — into
    the specimen's 실사례 line, verbatim from the sealed record;
  • it leaves every INTERPRETIVE field (증상 / 기전 / 탐지법 / 오적용) as an explicit TODO.

It never invents a case and never fills the mechanism story — those are the human's job,
and a draft is not catalog-ready until they are done. What it guarantees is that the
provenance is real and that no KILL/retraction silently goes uncollected.

Usage:
  python catalog/draft_specimen.py --ledger L.jsonl --claim <id>     # one claim
  python catalog/draft_specimen.py --ledger L.jsonl --latest          # newest retraction
  python catalog/draft_specimen.py --ledger L.jsonl --latest --write   # write DRAFT file
"""
import argparse
import json
import re
import sys
from pathlib import Path

# Category keyword heuristics — a SUGGESTION only; the human confirms/overrides.
# (dir, human label, ordered (keyword, ...) — first matching dir wins.)
_CATEGORIES = [
    ("contamination", "데이터/인코딩 오염",
     ("leakage", "contamination", "오염", "train∩test", "encoding", "인코딩", "중복")),
    ("gaming", "게이밍/신기루",
     ("gaming", "reward", "신기루", "trivial", "자명", "빈공간", "empty space",
      "majority", "다수클래스", "self-fulfilling", "artifact of the metric")),
    ("fn-guard", "거짓음성 가드",
     ("false negative", "거짓음성", "음성 성급", "구현 결함", "implementation flaw",
      "underpower", "검정력", "premature", "stand-in", "crippled")),
    ("self-catch", "자가적발",
     ("false positive", "too good", "self-caught", "자가적발", "오귀속",
      "misattribut", "착시", "너무 좋", "rescue", "post-hoc")),
]
_DEFAULT_CATEGORY = ("self-catch", "자가적발")  # an honestly-recorded KILL is usually a self-catch


def _slug(text: str) -> str:
    """kebab-case an id/claim into a filename-safe slug."""
    text = re.sub(r"[_\s]+", "-", text.strip().lower())
    text = re.sub(r"[^a-z0-9가-힣-]", "", text)
    text = re.sub(r"-{2,}", "-", text).strip("-")
    return text or "specimen"


def _suggest_category(reason: str) -> tuple[str, str]:
    low = reason.lower()
    for dir_, label, kws in _CATEGORIES:
        if any(k.lower() in low for k in kws):
            return dir_, label
    return _DEFAULT_CATEGORY


def _load_records(ledger: Path):
    """Return (list of all entries) parsed from a JSONL ledger."""
    out = []
    for line in ledger.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            out.append(json.loads(line))
        except json.JSONDecodeError:
            continue
    return out


def _find_retraction(records, claim_id, latest):
    retractions = [e for e in records if e.get("_type") == "retraction"]
    if claim_id:
        for e in retractions:
            if e.get("claim_id") == claim_id:
                return e
        return None
    if latest:
        return retractions[-1] if retractions else None
    return None


def _find_prereg(records, claim_id):
    """First preregistration entry for claim_id (skips witness/anchor/retraction)."""
    for e in records:
        if e.get("claim_id") == claim_id and e.get("_type") is None:
            return e
    return None


def _one_line(text: str, width: int = 100) -> str:
    """Collapse whitespace to a single line and clip for the summary/실사례."""
    s = " ".join(text.split())
    return s if len(s) <= width else s[: width - 1] + "…"


def draft(ledger: Path, claim_id=None, latest=False) -> dict | None:
    """Build a specimen draft dict from a sealed retraction. Returns None if not found."""
    records = _load_records(ledger)
    ret = _find_retraction(records, claim_id, latest)
    if ret is None:
        return None
    cid = ret.get("claim_id", "?")
    reason = ret.get("reason", "")
    seal = ret.get("seal", "?")
    pre = _find_prereg(records, cid)
    cat_dir, cat_label = _suggest_category(reason)
    slug = _slug(cid)
    provenance = (
        f"{ledger.name} — claim_id={cid} · retraction seal={seal}"
        + (f" · sealed criterion={pre.get('seal')}" if pre and pre.get("seal") else "")
    )
    body = f"""# {slug} — TODO: <표본 이름>

> TODO: one-line English summary (AI-skimmer first line).

<!-- 🦋 DRAFT auto-generated by catalog/draft_specimen.py from a SEALED retraction.
     The 실사례 line below is transcribed verbatim from the ledger and is catalog-valid.
     Every other field is a TODO — the catalog forbids fabricated cases, so a human
     must write 증상/기전/탐지법/오적용 from the actual arc before this is catalog-ready.
     Suggested category: {cat_dir}/ ({cat_label}) — confirm or move. -->

- **증상(시그니처)**: TODO — 무엇이 보이면 이 착시를 의심하나 (관측된 신호)
- **기전**: TODO — 왜 이 착시가 생기나 (기제 — 원장 사유에서 도출, 창작 금지)
- **실사례**: {_one_line(reason, 220)}  \\
  출처: {provenance}
- **탐지법**: TODO — 어느 프로브/규율 체크가 잡나
- **오적용 주의**: TODO — 이 라벨을 붙이면 안 되는 경우 (양방향 방어)
"""
    return {
        "claim_id": cid,
        "slug": slug,
        "category_dir": cat_dir,
        "category_label": cat_label,
        "seal": seal,
        "provenance": provenance,
        "body": body,
    }


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--ledger", required=True, help="path to the JSONL ledger")
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--claim", help="claim_id of the retracted claim")
    g.add_argument("--latest", action="store_true", help="use the newest retraction")
    ap.add_argument("--out", help="write the draft to this exact path")
    ap.add_argument("--write", action="store_true",
                    help="write to catalog/<category>/<slug>.DRAFT.md (next to this script)")
    a = ap.parse_args(argv)

    led = Path(a.ledger)
    if not led.exists():
        print(f"no ledger at {led}", file=sys.stderr)
        return 2
    d = draft(led, claim_id=a.claim, latest=a.latest)
    if d is None:
        who = a.claim or "latest"
        print(f"no retraction found for {who!r} in {led.name} — "
              "nothing to collect (a specimen needs a sealed retraction).",
              file=sys.stderr)
        return 1

    if a.out or a.write:
        if a.out:
            dest = Path(a.out)
        else:
            dest = Path(__file__).resolve().parent / d["category_dir"] / f"{d['slug']}.DRAFT.md"
        dest.parent.mkdir(parents=True, exist_ok=True)
        if dest.exists():
            print(f"refusing to overwrite existing {dest} — "
                  "edit it or pass a different --out.", file=sys.stderr)
            return 3
        dest.write_text(d["body"], encoding="utf-8")
        print(f"🦋 DRAFT written: {dest}")
        print(f"   category (suggested): {d['category_dir']}/  · provenance: {d['provenance']}")
        print("   → complete 증상/기전/탐지법/오적용 by hand, then rename .DRAFT.md → .md")
    else:
        sys.stdout.write(d["body"])
    return 0


if __name__ == "__main__":
    sys.exit(main())
